# Generated by Django 2.0.3 on 2018-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'published'), (2, 'draft'), (3, 'deleted')], default=1),
        ),
    ]
