# Generated by Django 2.0.3 on 2018-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180403_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'published'), (2, 'draft'), (3, 'deleted')], default=1),
        ),
    ]
